config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'students#welcome', as: 'welcome'
  resources :students
  resources :projects
  resources :pitches do
    post '/comments', to: 'comments#create', as: 'comments'
  end
  get '/login', to: "sessions#new", as: 'login'
  get '/sessions', to: 'sessions#destroy', as: 'logout'
  post '/sessions', to: "sessions#create", as: 'sessions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pitch
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :student
  has_many :comments
  validates :title, :content, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :student
  before_save :sanitize_website

  def sanitize_website
    if self.url_link.nil?
      nil
    elsif !self.url_link.include?(".com")
      self.url_link = self.url_link + ".com"
      if !self.url_link.include?("htt")
        self.url_link = "http://" + self.url_link
      end
    elsif !self.url_link.include?("htt")
      self.url_link = "http://" + self.url_link
    end
  end

  # i need to when people put .com.com

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :projects
  has_many :pitches
  has_many :comments, through: :pitches
  has_secure_password
  has_one_attached :profile_picture
  validates :email, uniqueness: true
  validates_length_of :password, :in => 6..20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_student, :logged_in?

  def current_student
    if session[:student_id]
      @student = Student.find_by(id: session[:student_id])
    else
    end
  end

  def logged_in?
    !!current_student
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

  def matching_student
    if current_student && current_student.id != params[:id].to_i
      redirect_to student_path(current_student) #error page down the line
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.pitch_id = params[:pitch_id]
    @comment.save
    redirect_to pitch_path(@comment.pitch)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :authorized
  skip_before_action :authorized, only: [:index, :show]
    def index
      @pitches = Pitch.all
    end

    def show
      @pitch = Pitch.find(params[:id])
      @comments = @pitch.comments
      @comment = Comment.new
    end

    def edit
      @pitch = Pitch.find(params[:id])
    end

    def update
      @pitch = Pitch.find(params[:id])
      @pitch.update(pitch_params)
      redirect_to @pitch
    end

    def new
      @pitch = Pitch.new
    end

    def create
      @pitch = Pitch.new(pitch_params)
      @pitch.student_id = session[:student_id] #finding the session that belongs to the pitch
      if @pitch.valid?
        @pitch.save
        redirect_to @pitch
      else
        render :new
      end
    end

    def destroy

    end

    def pitch_params
      params.require(:pitch).permit(:title, :content)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :authorized


  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.student_id = session[:student_id]
    if @project.valid?
      @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name,:url_link)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #login
  def new

  end
 #check if password is correct for this student
  def create
    student = Student.find_by(email: params[:email])
    if student && student.authenticate(params[:password])
      session[:student_id] = student.id
      redirect_to student_path(student)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:student_id)
    redirect_to welcome_url
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authorized
  before_action :matching_student, only: [:edit, :update, :destroy]
  skip_before_action :authorized, only: [:welcome, :index, :new, :create, :show]

  def welcome
    # redirect_to current_student
    render :welcome #a welcome page
  end

  def index
    @students = Student.with_attached_profile_picture
  end

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.valid?
      @student.save
      # first time naming student_id 29
      session[:student_id] = @student.id #
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to student_path(@student)

  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:name, :bio, :email, :password, :password_confirmation, :profile_picture, :langauge)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccessAlums</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Access Alums</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Profile", student_path(current_student), class: 'nav-link' %>
            <!-- <a class="nav-link" href="">Portfolio</a> -->
          </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="/pitches">Pitches</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/projects">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/students">Students</a>
          </li>
        </ul>
        <ul class="navbar-nav mr-right">
          <!-- conditional logic for current user and if they're logged in or not -->
          <!-- login and logout buttons here -->
          <!-- Welcome, current_user name -->
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Welcome, #{current_student.name}", student_path(current_student), class: "nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to "Log out", logout_path, method: 'delete', class: "nav-link" %>
          </li>
          <% else %>
            <li><%= link_to "Log In", login_path, class: "nav-link" %></li>
            <li><%= link_to "Sign Up", new_student_path(@student), class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>


    <div id="yield_div">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pitches/edit.html.erb
<%= form_for @pitch,method: "put" do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :value => @pitch.title %>

  <%= f.label :content %>
  <%= f.text_area :content, :alias => params[:@content] %>
<!--  I have no idea why the above code works-->
  <%= f.submit %>
<% end %>

app/views/pitches/index.html.erb
<%= link_to "New Pitch", new_pitch_path %>

<% @pitches.each do |pitch| %>
<li><%= link_to pitch.title, pitch%> <strong>Content: </strong> <%= pitch.content %></li>
<% end %>



<!--
create_table "pitches", force: :cascade do |t|
  t.string "title"
  t.text "content"
  t.integer "student_id"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end -->

app/views/pitches/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<link rel="stylesheet" href="application.scss">
<body>
  <div id="container">
    <div id="header">
      <%= form_for @pitch do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.submit %>
      <% end %>

    </div>
    <div id="footer">
      Copyright &copy; 2018 Charlie Tung & Eric Razor
    </div>
  </div>
</body>
</html>

app/views/pitches/show.html.erb
<center style="color:white">
<%= @pitch.title %>
<%= @pitch.content %>
<!-- <%= @pitch.student_id %></li> -->

<ul>
<% @comments.each do |comment|  %>
<li>
<%= comment.content %>
</li>
<% end %>
</ul>

<%= form_for @comment, url: pitch_comments_path(@pitch) do |f| %>
  <%= f.text_field :content, placeholder: "Write a comment..." %>
  <%= f.submit  %> <br>

  <%= link_to "Edit Pitch", edit_pitch_path%>

<% end %>
</center>



<!-- create_table "pitches", force: :cascade do |t|
#   t.string "title"
#   t.text "content"
#   t.integer "student_id"
#   t.datetime "created_at", null: false
#   t.datetime "updated_at", null: false -->

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= form_for @project, method: "put" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url_link %>
  <%= f.text_field :url_link %>

  <%= f.submit "Update Project"%>



<% end %>

app/views/projects/index.html.erb
<button type="button" class="btn btn-secondary"><%= link_to "Add Project", new_project_path %></button>

<% @projects.each do |project| %>
<li><%= link_to project.name, project %> => <%= project.url_link %></li>
<% end %>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="application.scss">

    <title>Document</title>
  </head>
  <body>
    <div id="container">

      <div id="header">
        <%= form_for @project do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :url_link %>
        <%= f.text_field :url_link %>

        <%= f.submit %>

      <% end %>
    </div>

  </div>
  <div id="footer">
    Copyright &copy; 2018 Charlie Tung & Eric Razor
  </div>
</body>
</html>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="application.scss">

    <title>Document</title>
  </head>
  <body>
    <div id="container">

      <div id="header">
        <h1> SHOW PAGE FOR PROJECT</h1>
          <p style="color: blue"><%= @project.name %></p>
          <p><%= auto_link(@project.url_link.to_s) %></p>


        <% if current_student == @project.student %>
          <%= (link_to "Edit Project", edit_project_path) %>
        <% end %>
    </div>

  </div>
  <div id="footer">
    Copyright &copy; 2018 Charlie Tung & Eric Razor
  </div>
</body>
</html>

app/views/students/edit.html.erb
<!-- <h1>Edit Profile</h1>
<%= form_for @student do |f| %>
  <p>
    <%= f.label "Name" %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Biography" %>
  <br>
  <%= f.text_area :bio %>
  <br>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <br>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <br>
  <%= f.label "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.label "Programming languages" %>
  <%= f.text_field :langauge %> <br>
  <%= f.submit "Submit" %>
  </p>
<% end %>
<%= button_to "DESTROY #{@student.name}", student_path(@student), method: :delete, class: 'btn, btn-danger' %>
-->


<div class="container">
<h1>Edit Profile</h1>
<%= form_for @student do |f| %>
  <div class="form-group">
  <%= f.label "Name" %>
  <%= f.text_field :name, class: "form-control" %> <br>
</div>
  <div class="form-group">
  <%= f.label "Biography" %>
  <%= f.text_area :bio, class: "form-control" %> <br>
  </div>

  <div class="form-group">
  <%= f.label "Email" %>
  <%= f.text_field :email,class: "form-control" %> <br>
  </div>

  <div class="form-group">
    <%= f.label "Programming languages" %>
    <%= f.text_field :langauge, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label "Password" %>
  <%= f.password_field :password,class: "form-control" %> <br>
  </div>


  <div class="form-group">
  <%= f.label "Password Confirmation" %>
  <%= f.password_field :password_confirmation,class: "form-control" %> <br>
  </div>
  <div class="form-group">
  <%= f.label :profile_picture %>
  <br>
  <%= f.file_field :profile_picture %> <br>
  </div>


  <%= f.submit "Submit", class: "btn btn-secondary" %>
  <%= link_to "delete profile", student_path(@student), method: :delete, class: 'btn btn-danger' %>
<% end %>
</div>

app/views/students/index.html.erb
<center>
  <h1 >Student's index</h1>
  <% @students.each do |student| %>
  <li class="student_names"><%= link_to student.name, student_path(student) %></li>
  <% end %>
</center>

app/views/students/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<link rel="stylesheet" href="application.scss">
<body>
  <div id="container">
    <div id="header">
      <h1>Create a new student</h1>
      <%= form_for @student do |f| %>
        <%= f.label "Name" %>
        <%= f.text_field :name, class: "form-control" %> <br>

        <%= f.label "Biography" %>
        <%= f.text_area :bio, class: "form-control" %> <br>

        <%= f.label "Email" %>
        <%= f.text_field :email, class: "form-control" %> <br>

        <%= f.label "Password" %>
        <%= f.password_field :password, class: "form-control" %> <br>

        <%= f.label "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %> <br>

        <%= f.label "Programming languages" %>
        <%= f.text_field :langauge, class: "form-control" %> <br>
      <!--  multiple: true-->


        <%= f.label :profile_picture %>
        <%= f.file_field :profile_picture %> <br>


        <%= f.submit "Sign up" %>
      <% end %>
    </div>
    <div id="footer">
      Copyright &copy; 2018 Charlie Tung & Eric Razor
    </div>
  </div>
</body>
</html>
``

app/views/students/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="application.scss">

    <title>Document</title>
  </head>
  <body>

    <div id="container">

      <div id="header">
        <h1><%= @student.name.downcase.capitalize %>
          Profile
        </h1>

        <% if @student.profile_picture.attached? %>
          <!-- @post.image.present? will always return true, use attached? to check presence -->
          <p>
            <br>
            <%= image_tag @student.profile_picture, class: "student_image" %>
          </p>
        <% end %>

        <p>
          <label for="">Biography:</label>
          <br>
          <%= @student.bio %>
        </p>

        <p>
          <label for="">Email:</label>
          <br>
          <%= @student.email %>
        </p>

        <% @student.projects.each do |project| %>
          <b><%= link_to project.name.downcase.capitalize, project_path(project) %></b>
          <p><%= auto_link(project.url_link) %></p>
        <% end %>

        <b>Languages</b>
        <p><%= @student.langauge %></p>

        <% if current_student == @student %>
          <%= button_to "Edit Profile", edit_student_path(@student), method: :get, class: 'btn, btn-info'%>
        <% end %>
      </div>

    </div>
    <div id="footer">
      Copyright &copy; 2018 Charlie Tung & Eric Razor
    </div>

  </body>
</html>

app/views/students/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
  </head>
  <link rel="stylesheet" href="application.scss">

  <body>
    <div style="width: 800px;
    margin-left: auto;
    margin-right: auto;" id="container">

      <div style="text-align: center;" id="header">

        <% if current_student %>
          <h1>Welcome
            <%= current_student.name.capitalize %></h1>
          <%= link_to "Logout", logout_path %>
        <% else %>
          <h1>Welcome
          </h1>
          <%= link_to "Login", login_path %>
        <% end %>

      </div>
      <iframe  width="560" height="315" src="https://www.youtube.com/embed/ySZiJxNjeQI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="allowfullscreen"></iframe>

    </div>
    <div id="footer">
      Copyright &copy; 2018 Charlie Tung & Eric Razor
    </div>

  </body>

</html>

<!-- Add css and formatting later -->